name: Testing Workflows

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/arm-deploy@v1
        with:
          scope: subscription
          region: eastus
          additionalArguments: "--confirm-with-what-if"
          template: test.bicep
          
